from __future__ import annotations

from types import SimpleNamespace
import uuid

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.errors import AnalysisRunNotFoundError, AnalysisRunStatusConflictError
from app.assemblers.inherent_risk_assembler import InherentRiskAssembler
from app.config import PercentageInherentRiskScoringPolicy
from app.llm.client import (
    AzureExecutiveSummaryClient,
    AzureOpenAIClientSettings,
    AzureSummaryTimeoutError,
)
from app.llm.executive_summary import ExecutiveSummaryPromptConfig, ExecutiveSummaryPromptLoader
from app.models.database import QuestionAnalysisRun
from app.models.enums import ExecutiveSummaryStatus, RiskLevel
from app.repositories.analysis_repository import AnalysisRepository
from app.repositories.assessment_repository import AssessmentRepository
from app.services.executive_summary_service import ExecutiveSummaryService
from app.services.inherent_risk_service import InherentRiskService
from tests.conftest import add_question_with_options, add_response

pytestmark = pytest.mark.asyncio


class SequencedSummaryClient:
    def __init__(self, outputs):
        self.outputs = list(outputs)
        self.calls = 0
        self.payloads: list[dict[str, object]] = []
        self.model_name = "gpt-5.5-test"

    def generate_summary(self, prompt, payload):
        self.calls += 1
        self.payloads.append(payload)
        outcome = self.outputs.pop(0)
        if isinstance(outcome, Exception):
            raise outcome
        return outcome


def build_inherent_risk_service() -> InherentRiskService:
    return InherentRiskService(
        assessment_repository=AssessmentRepository(),
        analysis_repository=AnalysisRepository(),
        assembler=InherentRiskAssembler(),
        scoring_policy=PercentageInherentRiskScoringPolicy(),
    )


def build_executive_summary_service(prompt_path, llm_client) -> ExecutiveSummaryService:
    return ExecutiveSummaryService(
        assessment_repository=AssessmentRepository(),
        analysis_repository=AnalysisRepository(),
        inherent_risk_service=build_inherent_risk_service(),
        prompt_loader=ExecutiveSummaryPromptLoader(prompt_path),
        llm_client=llm_client,
    )


async def seed_completed_analysis(db_session: AsyncSession, seeded_assessment):
    question, options = await add_question_with_options(
        db_session,
        seeded_assessment["questionnaire_version_id"],
        risk_domain="Security",
        why_it_matters="Stored why-it-matters text.",
        options=[
            ("Selected", RiskLevel.HIGH, 3.0, "Stored risk signal text."),
            ("Maximum", RiskLevel.CRITICAL, 4.0, "Maximum security signal."),
        ],
    )
    await add_response(db_session, seeded_assessment["assessment_id"], question, options[0])
    inherent_risk_service = build_inherent_risk_service()
    run = await inherent_risk_service.create_analysis_run(db_session, seeded_assessment["assessment_id"], force=False)
    return uuid.UUID(run.analysisRunId)


async def test_valid_summary_is_persisted(db_session, seeded_assessment, executive_summary_prompt_path):
    analysis_run_id = await seed_completed_analysis(db_session, seeded_assessment)
    llm_client = SequencedSummaryClient(['Deterministic summary generated by GPT-5.5.'])
    service = build_executive_summary_service(executive_summary_prompt_path, llm_client)

    response = await service.generate(db_session, seeded_assessment["assessment_id"], analysis_run_id)
    run = await AnalysisRepository().get_latest_completed_snapshot(db_session, seeded_assessment["assessment_id"])

    assert response.executiveSummary.status == ExecutiveSummaryStatus.GENERATED
    assert response.executiveSummary.text == "Deterministic summary generated by GPT-5.5."
    assert run is not None
    assert run.executive_summary_text == "Deterministic summary generated by GPT-5.5."
    assert run.executive_summary_model == "gpt-5.5-test"
    assert run.executive_summary_prompt_version == "v1"
    assert run.executive_summary_input_hash is not None
    assert run.executive_summary_generated_at is not None


async def test_malformed_json_retries_once(executive_summary_prompt_path):
    class FakeResponses:
        def __init__(self):
            self.calls = 0
            self.outputs = ['{"summary":123}', '{"summary":"Recovered summary."}']

        def create(self, **kwargs):
            self.calls += 1
            return SimpleNamespace(output_text=self.outputs[self.calls - 1])

    fake_sdk_client = SimpleNamespace(responses=FakeResponses())
    client = AzureExecutiveSummaryClient(
        settings=AzureOpenAIClientSettings(
            endpoint="https://example.openai.azure.com",
            api_key="test-key",
            deployment="gpt-5.5-test",
            timeout_seconds=5.0,
            api_version="2024-10-21",
        ),
        client=fake_sdk_client,
    )
    prompt = ExecutiveSummaryPromptConfig(
        id="executive-summary",
        version="v1",
        system="Summarize the deterministic assessment.",
        user_template="{input_json}",
    )

    summary = client.generate_summary(prompt, {"assessment": "payload"})

    assert summary == "Recovered summary."
    assert fake_sdk_client.responses.calls == 2


async def test_timeout_returns_fallback(db_session, seeded_assessment, executive_summary_prompt_path):
    analysis_run_id = await seed_completed_analysis(db_session, seeded_assessment)
    llm_client = SequencedSummaryClient([AzureSummaryTimeoutError("Azure OpenAI request timed out.")])
    service = build_executive_summary_service(executive_summary_prompt_path, llm_client)

    response = await service.generate(db_session, seeded_assessment["assessment_id"], analysis_run_id)
    run = await db_session.get(QuestionAnalysisRun, response.analysisRunId)

    assert response.executiveSummary.status == ExecutiveSummaryStatus.FALLBACK
    assert "currently assessed as Critical inherent risk" in response.executiveSummary.text
    assert run is not None
    assert run.status == "completed_with_limitations"
    assert run.error_summary == "Azure OpenAI request timed out."


async def test_matching_input_hash_skips_llm_call(db_session, seeded_assessment, executive_summary_prompt_path):
    analysis_run_id = await seed_completed_analysis(db_session, seeded_assessment)
    llm_client = SequencedSummaryClient(["First summary."])
    service = build_executive_summary_service(executive_summary_prompt_path, llm_client)

    first = await service.generate(db_session, seeded_assessment["assessment_id"], analysis_run_id)
    second = await service.generate(db_session, seeded_assessment["assessment_id"], analysis_run_id, force=False)

    assert llm_client.calls == 1
    assert first.executiveSummary.text == second.executiveSummary.text


async def test_force_true_regenerates(db_session, seeded_assessment, executive_summary_prompt_path):
    analysis_run_id = await seed_completed_analysis(db_session, seeded_assessment)
    llm_client = SequencedSummaryClient(["First summary.", "Regenerated summary."])
    service = build_executive_summary_service(executive_summary_prompt_path, llm_client)

    await service.generate(db_session, seeded_assessment["assessment_id"], analysis_run_id)
    response = await service.generate(db_session, seeded_assessment["assessment_id"], analysis_run_id, force=True)

    assert llm_client.calls == 2
    assert response.executiveSummary.text == "Regenerated summary."


async def test_stored_risk_level_is_never_changed(db_session, seeded_assessment, executive_summary_prompt_path):
    analysis_run_id = await seed_completed_analysis(db_session, seeded_assessment)
    llm_client = SequencedSummaryClient(["Summary text."])
    service = build_executive_summary_service(executive_summary_prompt_path, llm_client)

    before = await AnalysisRepository().get_latest_completed_snapshot(db_session, seeded_assessment["assessment_id"])
    response = await service.generate(db_session, seeded_assessment["assessment_id"], analysis_run_id)
    after = await AnalysisRepository().get_latest_completed_snapshot(db_session, seeded_assessment["assessment_id"])

    assert response.executiveSummary.status == ExecutiveSummaryStatus.GENERATED
    assert before is not None and after is not None
    assert before.inherent_risk_level == after.inherent_risk_level == RiskLevel.CRITICAL


async def test_mocked_azure_client_only_no_live_call(db_session, seeded_assessment, executive_summary_prompt_path):
    analysis_run_id = await seed_completed_analysis(db_session, seeded_assessment)
    llm_client = SequencedSummaryClient(["Summary text."])
    service = build_executive_summary_service(executive_summary_prompt_path, llm_client)

    response = await service.generate(db_session, seeded_assessment["assessment_id"], analysis_run_id)

    assert response.executiveSummary.text == "Summary text."
    assert llm_client.calls == 1


async def test_missing_analysis_run_pair_raises_not_found(db_session, seeded_assessment, executive_summary_prompt_path):
    llm_client = SequencedSummaryClient(["Summary text."])
    service = build_executive_summary_service(executive_summary_prompt_path, llm_client)

    with pytest.raises(AnalysisRunNotFoundError):
        await service.generate(db_session, seeded_assessment["assessment_id"], uuid.uuid4())


@pytest.mark.parametrize("status", ["queued", "running", "failed"])
async def test_invalid_analysis_run_status_raises_conflict(
    db_session,
    seeded_assessment,
    executive_summary_prompt_path,
    status,
):
    run = QuestionAnalysisRun(
        id=uuid.uuid4(),
        assessment_id=seeded_assessment["assessment_id"],
        status=status,
        scoring_rule_version="inherent-risk-v1-percentage",
        inherent_risk_level=RiskLevel.NOT_ASSESSED.value,
    )
    db_session.add(run)
    await db_session.commit()

    llm_client = SequencedSummaryClient(["Summary text."])
    service = build_executive_summary_service(executive_summary_prompt_path, llm_client)

    with pytest.raises(AnalysisRunStatusConflictError) as exc_info:
        await service.generate(db_session, seeded_assessment["assessment_id"], run.id)

    assert exc_info.value.status == status
    assert llm_client.calls == 0
